Add the type property to the Standard schema
sul-dlss/cocina-models pull request #180
Opened 2020-10-30 15:30 UTC by aaron-collier

## Why was this change made?

Add `type` to `Standard` to address:

```
Error: #/components/schemas/Standard does not define properties: type (2585 errors)
Examples: druid:zw685dw6356, druid:hv751kj0082, druid:ft545jn7796, druid:pf602td9391, druid:hv022gv3986, druid:wt776rw3893, druid:tt596nz1569, druid:mn953qz8474, druid:mj707sx9198, druid:jr037zj8458
```

## How was this change tested?

N/A

## Which documentation and/or configurations were updated?

N/A

2020-10-30 16:06 UTC, jcoyne requested changes
Make sure you generate the models.

2020-10-30 18:37 UTC, jcoyne submitted a review, later dismissed

2020-10-30 19:16 UTC, jcoyne commented
@aaron-collier is this still necessary?  I was able to do this on prod with no issue:
```
druid = 'druid:zw685dw6356'
 item = Dor.find(druid)
desc_props = Cocina::FromFedora::Descriptive.props(mods: item.descMetadata.ng_xml)
Cocina::Models::Description.new(desc_props)
```

2020-10-30 19:17 UTC, jcoyne requested changes
@aaron-collier is this still necessary?  I was able to do this on prod with no issue:
```
druid = 'druid:zw685dw6356'
item = Dor.find(druid)
desc_props = Cocina::FromFedora::Descriptive.props(mods: item.descMetadata.ng_xml)
Cocina::Models::Description.new(desc_props)
```

2020-10-30 21:41 UTC, aaron-collier commented
Yes, I believe it is. Currently, prod is not producing the `standard` block as expected. For instance, druid `druid:xy581jd9710` should have a block like:

```
"standard": {
  "code": 'EPSG:4326',
  "type": 'coordinate reference system'
}
```

per the spec: https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_geo_extension.txt#L174

2020-10-30 22:29 UTC, jcoyne commented
@arcadiafalcone what is the difference between `type` as @aaron-collier called out and `value` as seen https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/50c5cf3b67cfefa19743881dec7c5a731eedf950/mods_cocina_mappings/mods_to_cocina_name.txt#L518

2020-10-30 23:32 UTC, aaron-collier commented
If I run the Cocina mapping against my geo branch with the current cocina-models I get:

```
Loading production environment (Rails 5.2.4.4)
2.7.0 :001 > druid = 'druid:nh901ng6523'
2.7.0 :002 > item = Dor.find(druid)
2.7.0 :003 > desc_props = Cocina::FromFedora::Descriptive.props(mods: item.descMetadata.ng_xml)
2.7.0 :004 > Cocina::Models::Description.new(desc_props)
Traceback (most recent call last):
        1: from (irb):4
Cocina::Models::ValidationError (#/components/schemas/Standard does not define properties: type)
```

If I point cocina-models at this branch, it works fine. That's the only way I know to verify.

2020-11-03 19:37 UTC, arcadiafalcone commented
I've removed type from the mappings. It differs from the other example jcoyne linked above in that there the value is the name of the standard, whereas "coordinate reference system" indicates what EPSG:4326 is a standard for. In any case it's not really necessary.

cocina_descriptive_metadata PR: https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/107

2020-11-03 19:53 UTC, aaron-collier commented
Closing per: https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/107

2020-11-03 19:53 UTC, closed without merging