Add missing language and type attributes
sul-dlss/cocina-models pull request #181
Opened 2020-10-30 21:07 UTC by aaron-collier

## Why was this change made?

This adds the `language` property to DescriptiveBasicValue to resolve:

```
Error: #/components/schemas/DescriptiveBasicValue does not define properties: language (349 errors)
Examples: druid:nh901ng6523, druid:yx344pr0923, druid:xy581jd9710, druid:vv853br8653, druid:tk635kd7152, druid:wb876vv6035, druid:xv866ss4847, druid:xq983jq4604, druid:xt444rj4703, druid:xs653hz4172
```

And `type` to Standard for a follow up that was surfaced during round trip testing.

## How was this change tested?

cocina-round-trip

## Which documentation and/or configurations were updated?

2020-10-30 21:19 UTC, jcoyne requested changes
Can you add a reference to what surfaced this in round trip testing? 

And can we resolve #180 first?

2020-10-30 21:27 UTC, aaron-collier commented
I should have checked, that `type` range a bell (#180). I'll try to resolve that first and clean this one up. Good catch.

2020-10-30 22:42 UTC, jcoyne commented
@aaron-collier I don't see this being triggered when I do:
```
druid = 'druid:nh901ng6523'
item = Dor.find(druid)
desc_props = Cocina::FromFedora::Descriptive.props(mods: item.descMetadata.ng_xml)
Cocina::Models::Description.new(desc_props)
```

Is there something I can do to trigger this bug before this fix?

2020-11-11 19:17 UTC, mjgiarlo commented
@jcoyne is anything more needed for this PR or can we ship it?

2020-11-11 19:56 UTC, jcoyne commented
@mjgiarlo I'd love to see the test that is breaking before we have this change.

2020-11-11 19:58 UTC, mjgiarlo commented
@aaron-collier can you reproduce this bug? If so, can you show @jcoyne ?

2020-11-11 20:24 UTC, aaron-collier commented
@mjgiarlo / @jcoyne This is raised when running the round trip validation on geo branch, I don't know any other way to show it:

```
Error: #/components/schemas/DescriptiveBasicValue does not define properties: language (216 errors)
Examples: druid:by600fq9386, druid:bm478xb9386, druid:bv796wg8835, druid:tw488zr0377, druid:vh749rw5179, druid:sw697tr7876, druid:vn511vy0583, druid:dr548nd9532, druid:pr866bv3057, druid:wx705rs6241
```

2020-11-11 20:55 UTC, jcoyne commented
@aaron-collier can you point to the "geo branch"?

2020-11-11 20:57 UTC, aaron-collier commented
@jcoyne https://github.com/sul-dlss/dor-services-app/pull/1163  -- though now there are spec failures that weren't there last night. So I'll take a look there, but that's all I have.

2020-11-11 21:01 UTC, closed without merging