Add properties for modeling the admin policy defaults
sul-dlss/cocina-models pull request #235
Opened 2021-03-17 21:03 UTC by jcoyne

**NOTE:  Changes to openapi.yml require updating openapi.yml for sdr-api and dor-services-app and generating models - see README.**

## Why was this change made?

Currently we're just using an unvalidated chunk of XML to convey these values, but we should migrated to explicit values.

## How was this change tested?

## Which documentation and/or configurations were updated?

2021-03-17 22:10 UTC, andrewjbtw commented
I think there are fields in defaultObjectRights that we are not mapping in the rightsMetadata yet. See https://github.com/sul-dlss/cocina-models/issues/236

There's only a small number of APOs, so we should be able to check all of the defaultObjectRights that currently exist to see if any have other data not being mapped.

2021-03-18 16:16 UTC, mjgiarlo approved these changes

2021-03-18 16:23 UTC, mjgiarlo requested changes
Do we need to do more analysis re: @andrewjbtw's question before we merge this?

2021-03-18 16:29 UTC, aaron-collier commented
@mjgiarlo I think we do, and likely should have a specific meeting like we did about version.

2021-03-18 18:28 UTC, justinlittman approved these changes

2021-03-18 18:28 UTC, justinlittman commented
Per discussion at today's standup, OK to proceed with this PR.

2021-03-18 18:28 UTC, merged