Mark fields that are not required as optional
sul-dlss/cocina-models pull request #245
Opened 2021-03-26 13:22 UTC by jcoyne

## Why was this change made?

this gives us a way to do an update where we clear a value without having to have all the values of a schema

Fixes #244 
## How was this change tested?

## Which documentation and/or configurations were updated?

2021-03-26 16:38 UTC, justinlittman requested changes
Can you add a spec for generator?

2021-03-26 17:28 UTC, jcoyne commented
@justinlittman you bet! I added one.

2021-03-30 17:33 UTC, ndushay requested changes
Couple of comment quibbles;  o.w. looks okay to merge but I think 

Since this change impacts every model, I think it warrants running the integration tests before rolling it to prod.  (that is, after gem is released with this change, deploy to qa and run integration tests).

2021-03-30 17:33 UTC, ndushay commented on lib/cocina/generator/schema_base.rb
> +      # Allows values to be not be provided. This allows smaller requests as not every field needs to be provided.
"to be not be provided"?  change to "not to be provided"?

2021-03-30 17:33 UTC, ndushay commented on lib/cocina/generator/schema_base.rb
> +      # Allows values to be set to nil. This is useful when doing an update and you want to clear out a value.
"Allows non-required values to be set to nil" ???

2021-03-31 04:17 UTC, jcoyne commented
@ndushay thanks for the constructive suggestions. Changes made.

2021-03-31 06:14 UTC, ndushay approved these changes
approving as my comment quibbles were addressed;  I also don't want to block this while I'm out with the 2nd jab reaction.  I stand by my statement about testing this via integration tests before rolling it to prod.

2021-03-31 15:07 UTC, merged