[HOLD] Add validation of associated names.
sul-dlss/cocina-models pull request #406
Opened 2022-04-14 17:24 UTC by justinlittman

closes #391

**NOTE:  Changes to openapi.yml require updating openapi.yml for sdr-api and dor-services-app and generating models - see README.**

## Why was this change made? 🤔
* More validation
* Code re-use

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-04-14 17:27 UTC, justinlittman commented on lib/cocina/generator/generator.rb
> -        'dro_rights_description_builder.rb',
These were moved into own module, so no longer needed here.

2022-04-14 17:27 UTC, justinlittman commented on lib/cocina/models/builders/dro_rights_description_builder.rb
> +# frozen_string_literal: true
This is just a move.

2022-04-14 17:27 UTC, justinlittman commented on lib/cocina/models/builders/name_title_group_builder.rb
> +# frozen_string_literal: true
This is copied from DSA.

2022-04-14 17:27 UTC, justinlittman commented on lib/cocina/models/builders/rights_description_builder.rb
> +# frozen_string_literal: true
This is a move.

2022-04-14 17:27 UTC, justinlittman commented on lib/cocina/models/builders/title_builder.rb
> +# frozen_string_literal: true
This is a move.

2022-04-15 14:51 UTC, jcoyne requested changes
This PR is very large and challenging to review. Can you do the moves in a separate PR?

2022-04-18 14:27 UTC, justinlittman commented
This was tested on sdr-deploy.

2022-04-18 14:28 UTC, jcoyne approved these changes

2022-04-18 14:28 UTC, merged